SCREEN 0
CLS

'''''' THIS IS AN ADVANCED VERSION OF PRIME LOCATOR - IT HAS BEEN
'''''' REWRITTEN AND OPTIMISED FOR SPEED. (c) Timothy Carpenter
'''''' TYPING PLACE HOLDERS : ' 12345678901234567890
'''''' number~&& = 2 ^ 63 - 1  ' 9223372036854775807  - I FIGURED THE ERROR IS FOR NUMBERS GREATER THAN SIGNED INTEGER TYPES > 2^63 -1
'''''' number~&& = 2 ^ 64 - 39 ' 18446744074709551577 - IF THIS NUMBER PROCEEDS A SMALLER NUMBER THE COMPILER FAILS WITH 1 ERROR, HOWEVER
'''''' - IF THIS NUMBER PRECEDES A SMALLER NUMBER IN FOR/NEXT LOOP THEN COMPILER IGNORES FOR/NEXT LOOP !!!
''''''
'''''' In file included from qbx.cpp:2226:
'''''' ./../temp/main.txt:10:22: error: integer literal is too large to be represented in any integer type
'''''' fornext_finalvalue2= 18446744074709551577ull ;
''''''                      ^
'''''' 1 error generated.

'''''' THE FOLLOWING IS THE ORIGIONAL CODE THAT FAILED WITHOUT THE COMPILER CREATING AN ERROR MESSAGE...

''''''<<< START OF CODE:
'''
'''COLOR 12
'''
'''FOR number~&& = 18446744073709551615 TO 2147483647 STEP -2
'''
'''LOCATE 1, 1
'''PRINT "CHECKING:", number~&&
'''
'''NUMB$ = RIGHT$(STR$(number~&&), 1)
'''IF NUMB$ = "5" GOTO LNSKIP1
'''
'''FOR LONGDIV~&& = 3 TO INT(SQR(number~&&)) STEP 2
'''
'''NUMB$ = RIGHT$(STR$(LONGDIV~&&), 1)
'''IF NUMB$ = "5" GOTO LDSKIP1
'''
'''LOCATE 3, 1
'''PRINT LONGDIV~&&
'''
'''    IF number~&& MOD LONGDIV~&& = 0 THEN EXIT FOR
'''LDSKIP1:
'''NEXT LONGDIV~&&
'''
'''IF LONGDIV~&& > INT(SQR(number~&&) - 1) THEN
'''COLOR 14
'''PRINT number~&&;
'''COLOR 12
'''END IF
'''
'''LNSKIP1:
'''
'''NEXT number~&&
'''
'''END
'''''' >>> END OF CODE:

' THE FOLLOWING CODE WORKS AS EXPECTED...  -  HINT: 9223372036854775783 IS THE FIRST PRIME NUMBER IN SEQUENCE...

FOR number~&& = 9223372036854775807 TO 2147483649 STEP -2 ' SMALLER NUMBERS EXECUTE MUCH FASTER...

    NUMB$ = RIGHT$(STR$(number~&&), 1)
    IF NUMB$ = "5" GOTO LNSKIP1 ' IF NUMBER ENDS WITH 5 IT IS DIVISIBLE BY 5 NOT PRIME SO SKIP IT

    FOR LONGDIV~&& = 3 TO INT(SQR(number~&&)) STEP 2 ' DIVIDE NUMBER CHECKING STARTING WITH 3

        NUMB$ = RIGHT$(STR$(LONGDIV~&&), 1)
        IF NUMB$ = "5" GOTO LDSKIP1 ' IF DIVISER ENDS WITH 5 THEN SKIP IT FOR MORE SPEED

        LOCATE 1, 22
        COLOR 14
        PRINT "PRIMES";
        COLOR 12
        LOCATE 1, 30
        PRINT "CHECKING:"; number~&&; LONGDIV~&&;
        IF INKEY$ = CHR$(27) THEN END ' END PROGRAM IF ESCAPE KEY IS PRESSED...
        IF INKEY$ = "p" THEN SLEEP ' PAUSE PROGRAM IF "p" IS PRESSED...

        IF number~&& MOD LONGDIV~&& = 0 THEN EXIT FOR ' THE LINE CHECKS FOR PRIME
        LDSKIP1:
    NEXT LONGDIV~&&

    IF LONGDIV~&& > INT(SQR(number~&&) - 1) THEN 'PRINT PRIME NUMBERS IN YELLOW
        COLOR 14
        LOCATE 24, 1
        PRINT number~&&;
        LOCATE 25, 1
        PRINT
        COLOR 12 'RETURN TO DEFAULT COLOR OF SEARCH
    END IF

    LNSKIP1:

NEXT number~&&

END

